### ISSUE TITLE
fail compilation with vs 2010

### ISSUE THREAD

**Issue by vryy** [filiatra/gismo#19]
Hello

The compilation with VS 2010 is failed with the error message below>

6>D:\Documents\gismo\src\gsIO/gsReadFile.h(198): error C2248: 'std::unique_ptr<_Ty>::unique_ptr' : cannot access private member declared in class 'std::unique_ptr<_Ty>'
6>          with
6>          [
6>              _Ty=gismo::gsMultiPatch<double>
6>          ]
6>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\memory(2347) : see declaration of 'std::unique_ptr<_Ty>::unique_ptr'
6>          with
6>          [
6>              _Ty=gismo::gsMultiPatch<double>
6>          ]
6>          D:\Documents\gismo\src\gsIO/gsReadFile.h(197) : while compiling class template member function 'gismo::gsReadFile<T>::operator gismo::gsMultiPatch<T>(void)'
6>          with
6>          [
6>              T=double
6>          ]
6>          ..\..\examples\tutorialAdaptiveCDR.cpp(62) : see reference to class template instantiation 'gismo::gsReadFile<T>' being compiled
6>          with
6>          [
6>              T=double
6>          ]
6>

This compiles fine with VS 2017 so there may be a problem with compatibility with std library on VS 2010. However, it would be nicer if there are some fixes.

**Comment by filiatra** [comment]
Hi,
thank you for your message, we have seen the problem,
https://cdash.ricam.oeaw.ac.at/viewBuildError.php?buildid=209111
and we will try to fix it,
best
Angelos

**Comment by filiatra** [comment]
Now fixed
