### ISSUE TITLE
how to assemble shape function matrix

### ISSUE THREAD

**Issue by ZekeJi** [filiatra/gismo#3]
I want get the shape function matrix, such as u=x-X, x=Σn N(u) Q    .X is Nurbs surface.
N=[N1_I N2_I ...]  I is the 3*3 identity matrix.
How can I get the N by gismo?can I get partial derivative with N?
Thank you!

**Comment by filiatra** [comment]
Hi, 

Can you explain this a little more? I am not sure I understand.

If B(x) is a nurbs surface and p is a point then the function
gsTensorNurbs<2>::deriv_into

called with point p will give you a matrix containing the partial derivatives of all non-zero basis functions of B  evaluated at p, arranged as a vector.
See here:
https://people.ricam.oeaw.ac.at/a.mantzaflaris/gismodoc/classgismo_1_1gsBasis.html#ace7e41a211c6f0ce892e6fd282f9ae96

for more details.

**Comment by hamidrezaatri** [comment]
Hi
How can I extract coordinates of control points in the program, e.g. : "tutorialAdaptRefinementTHB".

Thank you
