### ISSUE TITLE
Coefs

### ISSUE THREAD

**Issue by hamidrezaatri** [filiatra/gismo#5]
Hi
How can I extract coordinates of control points in the program, e.g. : "tutorialAdaptRefinementTHB" ?
Thank you

**Comment by filiatra** [comment]
Hi,

The coefficients of the input patch are given by:
 gsMultiPatch<real_t> patches;
...
gsMatrix<> & coefs = patches.patch(0).coefs(); 

For the solution:
gsField<> solField;
..
const gsMatrix<T> & solCoefs = solField.coeffcientVector(); 

or even

gsMultiPatch<> sol;
...
gsMatrix<T> & solCoefs3 = sol.patch(0).coefs(); 



best
Angelos

**Comment by hamidrezaatri** [comment]
Hi
Thank you very much for the extra help you gave me and I really appreciate for your guidance.  
I have another question; I do not know how to iterate over all elements of a parametric domain; in fact I do not know how to use "gsDomainIterator" in  "tutorialAdaptRefinementTHB".
Thank you in advance for your cooperation.
