### ISSUE TITLE
DomainIteration

### ISSUE THREAD

**Issue by hamidrezaatri** [filiatra/gismo#6]
Hi
Thank you very much for the extra help you gave me and I really appreciate for your guidance.  
I have another question; I do not know how to iterate over all elements of a parametric domain; in fact I do not know how to use "gsDomainIterator" in  "tutorialAdaptRefinementTHB".
Thank you in advance for your cooperation.

**Comment by filiatra** [comment]
Hi,

There is some info in the doxygen pages:
https://people.ricam.oeaw.ac.at/a.mantzaflaris/gismodoc/classgismo_1_1gsDomainIterator.html

Here is some code, copied from src/gsAssembler/gsAssembler.h

    // Initialize domain element iterator
    typename gsBasis<T>::domainIter domIt = bases[0].makeDomainIterator();
    
    // Start iteration over elements
    for (; domIt->good(); domIt->next() )
    {
        // Map the Quadrature rule to the element
        QuRule.mapTo( domIt->lowerCorner(), domIt->upperCorner(), quNodes, quWeights );
        
        // Perform required evaluations on the quadrature nodes
        visitor.evaluate(bases, /* *domIt,*/ *geoEval, quNodes);
        
        // Assemble on element
        visitor.assemble(*domIt, *geoEval, quWeights);
        
        // Push to global matrix and right-hand side vector
        visitor.localToGlobal(patchIndex, m_ddof, m_system);
    }

Here bases[0] can be e.g. a THB spline basis.
