### ISSUE TITLE
gsTensorNurbsBasis

### ISSUE THREAD

**Issue by hamidrezaatri** [filiatra/gismo#7]
Hi
when the input file is based on .xml file and the geometry is constructed according to gsTensorNurbs in the file, how can we get gsTHBSplineBasis form a gsTensorNurbsBasis??

Best

**Comment by filiatra** [comment]
Hi,

the THB spline basis should be created by discarding the nurbs-weights. The function gsTensorNurbsBasis::source() returns a gsTensorBSplineBasis, which is the original NURBS without weights.
